object CODE {
    const val SCHOOL_CODE = 1

    const val MECHANICAL_ENGINE_CODE = 101
    const val MECHANICAL_DESIGN_CODE = 102

    const val AUTOMATION_ENGINE_CODE = 201
    const val ROBOT_ENGINE_CODE = 202

    const val COMPUTER_SOFTWARE_ENGINE_CODE = 301
    const val COMPUTER_INFO_ENGINE_CODE = 302
    const val ARTIFICIAL_ENGINE_CODE = 303

    const val ELECTRICAL_ENGINE_CODE = 401
    const val INFO_ELECTRONIC_ENGINE_CODE = 402
    const val SEMICONDUCTOR_ENGINE_CODE = 403
    const val INFO_COMMUNICATION_ENGINE_CODE = 404
    const val FIRE_MANAGEMENT_CODE = 405

    const val BIOCHEMICAL_ENGINE_CODE = 501
    const val BIO_CONVERGENCE_ENGINE_CODE = 502
    const val ARCHITECTURE_CODE = 503
    const val INTERIOR_DESIGN_CODE = 504
    const val VISUAL_DESIGN_CODE = 505
    const val AR_VR_CONTENT_CODE = 506

    const val BUSINESS_ADMINISTRATION_CODE = 601
    const val TAX_ACCOUNTING_CODE = 602
    const val DISTRIBUTION_MARKETING_CODE = 603
    const val HOTEL_TOURISM_CODE = 604
    const val MANAGEMENT_INFORMATION_CODE = 605
    const val BIG_DATA_MANAGEMENT_CODE = 606

    const val UNDECLARED_MAJOR_CODE = 701
}